spring:
   datasource:
      url:   jdbc:sqlserver://localhost;databaseName=springbootdb      
      username:   sa
      password:   Projects@123
   jpa:
      generate-ddl:   false
      properties:
         hibernate:
            default_schema:   public
            dialect:   org.hibernate.dialect.SQLServer2012Dialect
            temp:
               use_jdbc_metadata_defaults:   false