spring:
   datasource:
      url:   jdbc:sqlserver://imagination-cbs.database.windows.net:1433;database=imagination-cbs      
      username:   yash@imagination-cbs
      password:   test@123
   jpa:
      show-sql: true
      generate-ddl:   false
      properties:
         hibernate:
            default_schema:   cbs
            dialect:   org.hibernate.dialect.SQLServer2012Dialect
            temp:
               use_jdbc_metadata_defaults:   false

   mail:
     protocol: smtp
     host: smtp.gmail.com
     username: ${SPRING_EMAIL_USERNAME}
     password: ${SPRING_EMAIL_PASSWORD}
     port: 587
     test-connection: false
     default-encoding: UTF-8
     properties:
       mail:
         smtp:
           auth: true
           starttls:
             enable: true

cbssecurity:
     enabled: false

cest_outcome:
  inside_ir35_pdf: https://imaginationcbs.blob.core.windows.net/cbs/IR35 Example PDF inside.pdf
  outside_ir35_pdf: https://imaginationcbs.blob.core.windows.net/cbs/IR35 Example PDF outside.pdf

logging:
  config: classpath:log4j2-local.yml              

azure:                                                                                                                                           
  storage:                                                                                             
   connectionString: DefaultEndpointsProtocol=https;AccountName=imaginationcbs;AccountKey=uE2RZa+UXuI++dhdKlSreySCJvxMVszBhvO1ZLha1W4wFSQi8P8dAx5qBX/wLU7xhPlsUbWtIXdrbDd0tKj5fg==;EndpointSuffix=core.windows.net               
   container:                                                          
     name: templates
     
internal_sourcing:
    email_to: ramesh.suryaneni@imagination.com,pappu.rout@imagination.com,mitul.deshmukh@imagination.com