spring:
   datasource:
      url:   ${SPRING_DATASOURCE_URL}
      username:   ${SPRING_DATASOURCE_USERNAME}
      password:   ${SPRING_DATASOURCE_PASSWORD}
   jpa:
      generate-ddl:   false
      properties:
         hibernate:
            default_schema:   ${SPRING_DATASOURCE_DBSCHEMA}
            dialect:   org.hibernate.dialect.SQLServer2012Dialect
            temp:
               use_jdbc_metadata_defaults:   false
  
cbssecurity:
     enabled: true

cest_outcome:
  inside_ir35_pdf: https://cbsbucketwa.blob.core.windows.net/cest-forms/IR35 Example PDF inside.pdf
  outside_ir35_pdf: https://cbsbucketwa.blob.core.windows.net/cest-forms/IR35 Example PDF outside.pdf
  
logging:
  config: classpath:log4j2-staging.yml                