spring:
   datasource:
      url:   jdbc:sqlserver://testcests.database.windows.net:1433;database=cbs-database      
      username:   cbsapp_admin
      password:   1%2wJ}4]qNVm#*E7n+@TtT
   jpa:
      generate-ddl:   false
      properties:
         hibernate:
            default_schema:   dbo
            dialect:   org.hibernate.dialect.SQLServer2012Dialect
            temp:
               use_jdbc_metadata_defaults:   false
  
cbssecurity:
     enabled: true

cest_outcome:
  inside_ir35_pdf: https://imaginationcbs.blob.core.windows.net/cbs/IR35 Example PDF inside.pdf
  outside_ir35_pdf: https://imaginationcbs.blob.core.windows.net/cbs/IR35 Example PDF outside.pdf            
               